repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "88"]
        language_version: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
        args: ["--max-line-length=88"]

- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: ./.venv/bin/pytest tests
    language: system
    types: [python]
    pass_filenames: false
    always_run: true