# Python CircleCI 2.0 configuration file
version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.11.3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create -n venv python=3.11 --yes
            conda activate venv
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            conda activate venv
            flake8 --exclude=venv* --statistics
            pytest -v --cov